#Global configuration
spring.application.name=ussd-api-master

#Tomcat configuration
server.port=9090

#Log level configuration
logging.level.root=info
logging.level.com.wirepick=debug
logging.level.org.springframework.web=debug



#database 
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
#driver for mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER

#JWT 
jwt.secret = your-256-bit-secret-key-here
#7 * 24 * 60 * 60 * 1000; // 7 days
jwt.access_token_validity = 604800000  

#URL
app.root.url = USSD-API/v2


