package com.app.ussd.exception;

public enum ErrorCodes {
	ID_NULL,
	SERVICE_CODE_NULL,
	ID_NOT_MATCH,
	ACCOUNT_NOT_FOUND,
	ACCOUNT_NOT_VALID,
	ACCOUNT_NAME_NULL,
	ACCOUNT_ALREADY_EXIST,
	EMAIL_ALREADY_EXIST,
	
	COVRAGE_NOT_FOUND,
	COVRAGE_NOT_VALID,
	COVRAGE_ALREADY_EXIST,
	
	//TODO Complete the rest of error code
	CLIENT_NOT_FOUND,
	CLIENT_NOT_VALID,
	
	SERVICE_NOT_FOUND,
	SERVICE_NOT_VALID,
	SERVICE_ALREADY_EXIST,
	
	
	SERVICE_CODE_NOT_FOUND,
	SERVICE_CODE_NOT_VALID,
	SERVICE_CODE_DEDICATED_ALREDAY_ASSIGNED,
	SERVICE_CODE_ALREADY_EXIST,
	
	
	ROUTE_MNO_NOT_FOUND,
	ROUTE_MNO_NOT_VALID,
	ROUTE_MNO_ALREADY_EXIST,
	
	
	MENU_NOT_FOUND,
	NEXT_MENU_NOT_FOUND,
	MENU_NOT_VALID,
	
	MNO_NOT_VALID,
	MNO_NOT_FOUND,
	MNO_ALREADY_EXIST,	
	
	MENU_OPTION_NOT_FOUND,
	MENU_OPTION_NOT_VALID,
	MENU_OPTION_EXIST,
	
	ENTREPRISE_NOT_FOUND,
	ENTREPRISE_NOT_VALID,
	
	USER_NOT_VALID,
	USER_NOT_FOUND,
	USER_EXIST,
	NO_USER_FOUND,
	
	NO_USSD_SESSION_FOUND,
	USSD_SESSION_NOT_FOUND,
	
	NO_USSD_TRANSACTION_FOUND,
	TRANSACTION_NOT_FOUND,
	
	BAD_CREDENTIALS,
	BAD_REQUEST,
	
	ROLE_NOT_VALID,
	ROLE_NOT_FOUND,
	ROLE_ALREADY_EXIST,
	
	PAYS_CODE_NOT_VALID,
	
	
	
}
